title: Exam 70-483
description: Csharp8 e Csharp9
meta: kg50GjPxJzeZrWjVtYbRE5i-xpi7UvYsf753E8JJR4A
google-site-verification: kg50GjPxJzeZrWjVtYbRE5i-xpi7UvYsf753E8JJR4A
github_username: https://github.com/shyoutarou
theme: jekyll-theme-midnight
